# Generated by Django 5.1.5 on 2025-02-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tips',
            field=models.JSONField(default=list),
        ),
    ]
